/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import utilitarios.Conexao;

/**
 *
 * @author Luis
 */
public class FrmPrincipal extends javax.swing.JFrame
{

    /**
     * Creates new form FrmPrincipal
     */
    
    public FrmPrincipal()
    {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldUsuario = new javax.swing.JTextField();
        jPasswordFieldSenha = new javax.swing.JPasswordField();
        jComboBoxNvlAcesso = new javax.swing.JComboBox();
        jButtonLimpar = new javax.swing.JButton();
        jButtonEntrar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabelUsuario = new javax.swing.JLabel();
        jLabelNvlAcesso = new javax.swing.JLabel();
        jLabelHoraAcesso = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuAdmin = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuProfessor = new javax.swing.JMenu();
        jMenuAluno = new javax.swing.JMenu();
        jMenuTreino = new javax.swing.JMenu();
        jMenuMensalidades = new javax.swing.JMenu();
        jMenuRelatorios = new javax.swing.JMenu();
        jMenuLogout = new javax.swing.JMenu();
        jMenuSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Gerenciamento de Academias");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Login"));

        jLabel1.setText("Usuário:");

        jLabel2.setText("Senha:");

        jLabel3.setText("Nível:");

        jComboBoxNvlAcesso.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Usuario", "Super Usuário" }));

        jButtonLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Actions-edit-clear-locationbar-rtl-icon.png"))); // NOI18N
        jButtonLimpar.setText("Limpar");
        jButtonLimpar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonLimparActionPerformed(evt);
            }
        });

        jButtonEntrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Actions-edit-clear-locationbar-ltr-icon.png"))); // NOI18N
        jButtonEntrar.setText("Entrar");
        jButtonEntrar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonEntrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonLimpar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextFieldUsuario)
                    .addComponent(jPasswordFieldSenha)
                    .addComponent(jComboBoxNvlAcesso, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButtonEntrar, jButtonLimpar});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jPasswordFieldSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBoxNvlAcesso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonLimpar)
                    .addComponent(jButtonEntrar))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jComboBoxNvlAcesso, jPasswordFieldSenha, jTextFieldUsuario});

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados"));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelHoraAcesso)
                    .addComponent(jLabelUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelNvlAcesso, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE))
                .addContainerGap(106, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelUsuario)
                .addGap(18, 18, 18)
                .addComponent(jLabelNvlAcesso)
                .addGap(18, 18, 18)
                .addComponent(jLabelHoraAcesso)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/academia logo.PNG"))); // NOI18N

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1ActionPerformed(evt);
            }
        });

        jMenuAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/admin-icon.png"))); // NOI18N
        jMenuAdmin.setText("Administrador");
        jMenuAdmin.setEnabled(false);

        jMenuItem2.setText("Usuários");
        jMenuAdmin.add(jMenuItem2);

        jMenuBar1.add(jMenuAdmin);

        jMenuProfessor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Person-Male-Light-icon.png"))); // NOI18N
        jMenuProfessor.setText("Professores");
        jMenuProfessor.setEnabled(false);
        jMenuBar1.add(jMenuProfessor);

        jMenuAluno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/User-Group-icon.png"))); // NOI18N
        jMenuAluno.setText("Alunos");
        jMenuAluno.setEnabled(false);
        jMenuAluno.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jMenuAlunoMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuAluno);

        jMenuTreino.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/weightlifting-icon.png"))); // NOI18N
        jMenuTreino.setText("Treinos");
        jMenuTreino.setEnabled(false);
        jMenuBar1.add(jMenuTreino);

        jMenuMensalidades.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Invoice-icon.png"))); // NOI18N
        jMenuMensalidades.setText("Mensalidades");
        jMenuMensalidades.setEnabled(false);
        jMenuBar1.add(jMenuMensalidades);

        jMenuRelatorios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/document-yellow-icon.png"))); // NOI18N
        jMenuRelatorios.setText("Relatórios");
        jMenuRelatorios.setEnabled(false);
        jMenuBar1.add(jMenuRelatorios);

        jMenuLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Log-Out-icon.png"))); // NOI18N
        jMenuLogout.setText("Logout");
        jMenuLogout.setEnabled(false);
        jMenuLogout.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jMenuLogoutMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuLogout);

        jMenuSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Close-2-icon.png"))); // NOI18N
        jMenuSair.setText("Sair");
        jMenuSair.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jMenuSairMouseClicked(evt);
            }
        });
        jMenuSair.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jMenuSairActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenuSair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(380, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(105, 105, 105))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 169, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuSairActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuSairActionPerformed
    {//GEN-HEADEREND:event_jMenuSairActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuSairActionPerformed

    private void jMenuSairMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jMenuSairMouseClicked
    {//GEN-HEADEREND:event_jMenuSairMouseClicked
        Object[] options =
        {
            "Sim", "Não"
        };
        int sd
                = JOptionPane.showOptionDialog(
                        null,
                        "Deseja Sair?",
                        "Saída do Programa",
                        JOptionPane.DEFAULT_OPTION,
                        JOptionPane.WARNING_MESSAGE,
                        null,
                        options,
                        options[0]);

        if (sd == 0)
        {
            dispose();
        }
    }//GEN-LAST:event_jMenuSairMouseClicked

    private void jButtonEntrarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonEntrarActionPerformed
    {//GEN-HEADEREND:event_jButtonEntrarActionPerformed
        if (jTextFieldUsuario.getText().equals("a") && (jPasswordFieldSenha.getText().equals("a")) 
                && jComboBoxNvlAcesso.getSelectedItem().equals("Usuario"))
        {
            JOptionPane.showMessageDialog(null, "Seja bem vindo " +jTextFieldUsuario.getText());
            jMenuAdmin.setEnabled(true);
            jMenuAluno.setEnabled(true);
            jMenuMensalidades.setEnabled(true);
            jMenuProfessor.setEnabled(true);
            jMenuRelatorios.setEnabled(true);
            jMenuTreino.setEnabled(true);
            jMenuLogout.setEnabled(true);

            jPanel1.setEnabled(false);
            jLabel1.setEnabled(false);
            jLabel2.setEnabled(false);
            jLabel3.setEnabled(false);
            jTextFieldUsuario.setEnabled(false);
            jPasswordFieldSenha.setEnabled(false);
            jComboBoxNvlAcesso.setEnabled(false);
            jButtonEntrar.setEnabled(false);
            jButtonLimpar.setEnabled(false);
            
            jLabelUsuario.setText("Usuário: " + jTextFieldUsuario.getText());
            jLabelNvlAcesso.setText("Nível de Acesso: " + jComboBoxNvlAcesso.getSelectedItem());
            jLabelHoraAcesso.setText("Sessão Iniciada: " + getDateTime());
            
        } else
        {
            JOptionPane.showMessageDialog(null, "Usuário ou senha incorretos!");
            jTextFieldUsuario.setText(null);
            jPasswordFieldSenha.setText(null);
        }
    }//GEN-LAST:event_jButtonEntrarActionPerformed

    private void jButtonLimparActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonLimparActionPerformed
    {//GEN-HEADEREND:event_jButtonLimparActionPerformed
        jTextFieldUsuario.setText(null);
        jPasswordFieldSenha.setText(null);
    }//GEN-LAST:event_jButtonLimparActionPerformed

    private void jMenuLogoutMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jMenuLogoutMouseClicked
    {//GEN-HEADEREND:event_jMenuLogoutMouseClicked
        JOptionPane.showMessageDialog(null, "Usuário desconectado!");
        jMenuAdmin.setEnabled(false);
        jMenuAluno.setEnabled(false);
        jMenuMensalidades.setEnabled(false);
        jMenuProfessor.setEnabled(false);
        jMenuRelatorios.setEnabled(false);
        jMenuTreino.setEnabled(false);
        jMenuLogout.setEnabled(false);

        jPanel1.setEnabled(true);
        jLabel1.setEnabled(true);
        jLabel2.setEnabled(true);
        jLabel3.setEnabled(true);
        jTextFieldUsuario.setEnabled(true);
        jPasswordFieldSenha.setEnabled(true);
        jComboBoxNvlAcesso.setEnabled(true);
        jButtonEntrar.setEnabled(true);
        jButtonLimpar.setEnabled(true);
        
        jTextFieldUsuario.setText(null);
        jPasswordFieldSenha.setText(null);
        
        jLabelHoraAcesso.setText(null);
        jLabelNvlAcesso.setText(null);
        jLabelUsuario.setText(null);
    }//GEN-LAST:event_jMenuLogoutMouseClicked

    private void jMenuAlunoMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jMenuAlunoMouseClicked
    {//GEN-HEADEREND:event_jMenuAlunoMouseClicked
       FrmAlunos alunos = new FrmAlunos();
        alunos.setVisible(true);
    }//GEN-LAST:event_jMenuAlunoMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
    {//GEN-HEADEREND:event_jButton1ActionPerformed
    }//GEN-LAST:event_jButton1ActionPerformed

    private String getDateTime() 
    { 
        DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss"); 
        Date date = new Date();
        return dateFormat.format(date); 
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonEntrar;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JComboBox jComboBoxNvlAcesso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelHoraAcesso;
    private javax.swing.JLabel jLabelNvlAcesso;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JMenu jMenuAdmin;
    private javax.swing.JMenu jMenuAluno;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenu jMenuLogout;
    private javax.swing.JMenu jMenuMensalidades;
    private javax.swing.JMenu jMenuProfessor;
    private javax.swing.JMenu jMenuRelatorios;
    private javax.swing.JMenu jMenuSair;
    private javax.swing.JMenu jMenuTreino;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordFieldSenha;
    private javax.swing.JTextField jTextFieldUsuario;
    // End of variables declaration//GEN-END:variables
}
